name       : perl-http-daemon
version    : '6.14'
release    : 7
source     :
    - https://cpan.metacpan.org/authors/id/O/OA/OALDERS/HTTP-Daemon-6.14.tar.gz : f0767e7f3cbb80b21313c761f07ad8ed253bce9fa2d0ba806b3fb72d309b2e1d
homepage   : https://metacpan.org/pod/HTTP::Daemon
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : HTTP::Daemon - a simple http server class
description: |
    Instances of the HTTP::Daemon class are HTTP/1.1 servers that listen on a socket for incoming requests. The HTTP::Daemon is a subclass of IO::Socket::INET, so you can perform socket operations directly on it too.
builddeps  :
    - perl-module-build
rundeps    :
    - perl-http-date
    - perl-http-message
    - perl-lwp-mediatypes
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
