name       : perl-http-daemon
version    : 6.01
release    : 6
source     :
    - https://cpan.metacpan.org/authors/id/G/GA/GAAS/HTTP-Daemon-6.01.tar.gz : 43fd867742701a3f9fcc7bd59838ab72c6490c0ebaf66901068ec6997514adc2
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : HTTP::Daemon - a simple http server class
description: |
    Instances of the HTTP::Daemon class are HTTP/1.1 servers that listen on a socket for incoming requests. The HTTP::Daemon is a subclass of IO::Socket::INET, so you can perform socket operations directly on it too.
rundeps    :
    - perl-http-date
    - perl-http-message
    - perl-lwp-mediatypes
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
