name       : perl-http-daemon
version    : '6.16'
release    : 8
source     :
    - https://cpan.metacpan.org/authors/id/O/OA/OALDERS/HTTP-Daemon-6.16.tar.gz : b38d092725e6fa4e0c4dc2a47e157070491bafa0dbe16c78a358e806aa7e173d
homepage   : https://metacpan.org/pod/HTTP::Daemon
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : HTTP::Daemon - a simple http server class
description: |
    Instances of the HTTP::Daemon class are HTTP/1.1 servers that listen on a socket for incoming requests. The HTTP::Daemon is a subclass of IO::Socket::INET, so you can perform socket operations directly on it too.
builddeps  :
    - perl-module-build
rundeps    :
    - perl-http-date
    - perl-http-message
    - perl-lwp-mediatypes
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
